receivers:
  #jaeger:
  #  endpoint: 0.0.0.0:55678
  opencensus:
    endpoint: "0.0.0.0:55678"
  otlp:
    endpoint: "0.0.0.0:55680"
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
          - targets: ['localhost:8888']
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '.*grpc_io.*'
            action: drop
  zipkin:
    endpoint: 0.0.0.0:3000

processors:
  attributes:
    actions:
    - key: environment
      value: "observe2020"
      action: insert
  batch:
  queued_retry:

exporters:
  #jaeger:
  #  endpoint: jaeger-all-in-one:14250
  logging:
  #prometheus:
  #  endpoint: "0.0.0.0:8889"
  #  namespace: promexample
  #  const_labels:
  #    label1: value1
  #sapm:
  #  access_token: "TOKEN"
  #  endpoint: "https://ingest.us0.signalfx.com/v2/trace"
  #zipkin:
  #  url: "http://zipkin-all-in-one:9411/api/v2/spans"
  #  format: proto

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1888
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging]
    traces:
      receivers: [zipkin, opencensus, otlp]
      processors: [batch, attributes, queued_retry]
      exporters: [logging]
